/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p47.reto4.vista;

import java.sql.SQLException;

import javax.print.attribute.standard.DialogTypeSelection;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

import java.awt.*;
import java.awt.event.*;

import utp.misiontic2022.c2.p47.reto4.modelo.dao.ModeloDatos;
import utp.misiontic2022.c2.p47.reto4.controlador.ControladorRequerimientos;

/**
 *
 * @author ASUS
 */
public class ConsultaGUI extends javax.swing.JFrame {
    public static final ControladorRequerimientos controlador = new ControladorRequerimientos();

    /**
     * Creates new form ConsultaGUI
     */
    Dialog miDialogo1 = new Dialog( this, "Consulta 1");
    Dialog miDialogo2 = new Dialog( this, "Consulta 2");
    Dialog miDialogo3 = new Dialog( this, "Consulta 3");
    public ConsultaGUI() {
        initComponents();
        miDialogo1.addWindowListener( new Conclusion1() );
        miDialogo2.addWindowListener( new Conclusion2() );
        miDialogo3.addWindowListener( new Conclusion3() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        consulta_1 = new javax.swing.JButton();
        consulta_2 = new javax.swing.JButton();
        consulta_3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel1.setText("Conocer el nombre, apellidos y salarios de los lideres cuyo segundo apellido sea 'Ortiz'");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setText("Transformar y obtener el nombre de los lideres donde la primera letra sea en minúscula y las demás en mayúscula");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setText("Saber la suma de los salarios de todos los lideres por su ciudad de residencia");

        consulta_1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        consulta_1.setText("Consulta 1");
        consulta_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_1ActionPerformed(evt);
            }
        });

        consulta_2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        consulta_2.setText("Consulta 2");
        consulta_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_2ActionPerformed(evt);
            }
        });

        consulta_3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        consulta_3.setText("Consulta 3");
        consulta_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consulta_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(consulta_2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(283, 283, 283))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(consulta_3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(consulta_1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(consulta_2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(consulta_3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consulta_1ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            ModeloDatos modelo;
            modelo = controlador.consultarRequerimiento1();
            JTable tabla = new JTable(modelo);
            miDialogo1.setSize(500, 150);
            // Hace que el dialogo aparezca en la pantalla
            miDialogo1.add(tabla); 
            miDialogo1.setVisible(true); 
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void consulta_2ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            ModeloDatos modelo;
            modelo = controlador.consultarRequerimiento2();
            JTable tabla = new JTable(modelo);
            miDialogo2.setSize(200, 500);
            // Hace que el dialogo aparezca en la pantalla
            miDialogo2.add(new JScrollPane(tabla)); 
            miDialogo2.setVisible(true);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void consulta_3ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            ModeloDatos modelo;
            modelo = controlador.consultarRequerimiento3();
            JTable tabla = new JTable(modelo);
            miDialogo3.setSize(200, 323);
            // Hace que el dialogo aparezca en la pantalla
            miDialogo3.add(tabla); 
            miDialogo3.setVisible(true);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    class Conclusion1 extends WindowAdapter {
        public void windowClosing( WindowEvent evt ) {
            // Concluye la aplicacion cuando el usuario cierra la ventana
            miDialogo1.setVisible(false);
            }
        }

        class Conclusion2 extends WindowAdapter {
            public void windowClosing( WindowEvent evt ) {
                // Concluye la aplicacion cuando el usuario cierra la ventana
                miDialogo2.setVisible(false);
                }
            }

            class Conclusion3 extends WindowAdapter {
                public void windowClosing( WindowEvent evt ) {
                    // Concluye la aplicacion cuando el usuario cierra la ventana
                    miDialogo3.setVisible(false);
                    }
                }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consulta_1;
    private javax.swing.JButton consulta_2;
    private javax.swing.JButton consulta_3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
